# Generated by Django 4.1.3 on 2023-02-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_program_project_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_sigla',
            new_name='sigla',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Fecha de Publicación'),
        ),
    ]
