# Generated by Django 4.1.3 on 2023-04-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_year_project_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='number',
        ),
    ]
