# Generated by Django 4.1.3 on 2023-02-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_type_alter_project_program_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Typo de Proyecto')),
                ('guide', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.type', verbose_name='Tipo de Proyecto'),
        ),
        migrations.AddField(
            model_name='type',
            name='guides',
            field=models.ManyToManyField(related_name='guides', to='projects.guide'),
        ),
    ]
