# Generated by Django 4.1.3 on 2023-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
