# Generated by Django 4.1.3 on 2023-03-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portada',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Año'),
        ),
    ]
