# Generated by Django 4.1.3 on 2023-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_portada_alter_project_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='eett',
            field=models.FileField(null=True, upload_to='documents', verbose_name='EETT'),
        ),
        migrations.AddField(
            model_name='project',
            name='presupuesto',
            field=models.FileField(null=True, upload_to='documents', verbose_name='Presupuesto'),
        ),
    ]
