# Generated by Django 4.1.3 on 2023-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_eett_project_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='afterimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='beaforeimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
