# Generated by Django 4.1.3 on 2023-03-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_afterimage_alter_project_beaforeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='beaforeimage',
            new_name='beforeimage',
        ),
    ]
