# Generated by Django 4.1.3 on 2023-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_beaforeimage_project_beforeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='beforeimage',
        ),
    ]
