# Generated by Django 4.1.3 on 2023-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_beforeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beforeimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen Antes'),
        ),
    ]
