# Generated by Django 4.1.3 on 2023-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_beforeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube'),
        ),
    ]
