version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn projectbank.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8000:8001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=projectbank.settings.dev
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}

  proxy:
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/home/app/web/staticfiles

volumes:
  postgres_data:
  

