version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn projectbank.wsgi:application --bind 0.0.0.0:8081"
    volumes:
      - ./staticfiles:/staticfiles
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=projectbank.settings.dev

volumes:
  postgres_data:
