version: '3.8'

services:
  banco2back_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_bpV2:/var/lib/postgresql/data/
    networks:
      - development

  banco2back:
    build: .
    command: bash -c "python manage.py migrate && gunicorn projectbank.wsgi:application --bind 0.0.0.0:8083"
    volumes:
      - .:/app
    networks:
      - development
    depends_on:
      - banco2back_db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=projectbank.settings.dev
    ports:
      - "8083:8083"

volumes:
  postgres_data_bpV2:

networks:
  development:
    external: true
