# Generated by Django 4.1.3 on 2023-06-24 00:00

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=60, verbose_name='Nombre completo (obligatorio)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico institucional (obligatorio)')),
                ('organization', models.CharField(max_length=30, verbose_name='Organización a la que perteneces (obligatorio)')),
                ('contact_reason', models.CharField(choices=[('sugerencia', 'Sugerencia'), ('consulta', 'Consulta por programa'), ('documento', 'Falta un documento'), ('falla', 'Falla en la plataforma')], max_length=30, verbose_name='Razón de contacto (obligatorio)')),
                ('message', models.TextField(verbose_name='Comentario (obligatorio)')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
