# Generated by Django 4.2.2 on 2023-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Comentario (obligatorio)'),
        ),
    ]
