# Generated by Django 4.2.2 on 2023-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Título documento'),
        ),
        migrations.AlterField(
            model_name='historicaldocuments',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Título documento'),
        ),
    ]
