# Generated by Django 4.2.2 on 2023-09-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_historicaldocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicaldocuments',
            name='state',
        ),
    ]
