# Generated by Django 4.2.2 on 2023-09-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_guide_program_and_more'),
        ('documents', '0005_remove_documents_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.program'),
        ),
        migrations.AddField(
            model_name='historicaldocuments',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.program'),
        ),
    ]
