# Generated by Django 4.2.2 on 2023-10-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documents_program_historicaldocuments_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDocuments',
        ),
    ]
