# Generated by Django 4.2.2 on 2023-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovative_projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInnovativeProjects',
        ),
    ]
