# Generated by Django 4.2.2 on 2023-09-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovative_projects', '0003_historicalinnovativeprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinnovativeprojects',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinnovativeprojects',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innovativeprojects',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innovativeprojects',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalinnovativeprojects',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RevisionSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_portada', models.BooleanField(default=False, verbose_name='Foto de portada con problemas')),
                ('approved_gallery', models.BooleanField(default=False, verbose_name='Fotos de la galería con problemas')),
                ('approved_web_source', models.BooleanField(default=False, verbose_name='Error en la fuente o enlace')),
                ('approved_section_two', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_section_two', to='innovative_projects.innovativeprojects')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_title', models.BooleanField(default=True, verbose_name='Error en el título')),
                ('approved_description', models.BooleanField(default=True, verbose_name='Error en la descripción del proyecto')),
                ('approved_program', models.BooleanField(default=True, verbose_name='Programa incorrecto')),
                ('approved_section_one', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_section_one', to='innovative_projects.innovativeprojects')),
            ],
        ),
    ]
