# Generated by Django 4.2.2 on 2023-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_historicaltype_historicalproject_historicalprogram_and_more'),
        ('innovative_projects', '0004_historicalinnovativeprojects_evaluated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionsectionone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='revisionsectiontwo',
            name='project',
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='program',
            field=models.ManyToManyField(blank=True, to='projects.program', verbose_name='Programa (obligatorio)'),
        ),
    ]
