# Generated by Django 4.2.2 on 2023-09-26 21:49

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('innovative_projects', '0007_alter_revisionsectionone_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinnovativeprojects',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(280, 'La descripción debe tener al menos 280 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='historicalinnovativeprojects',
            name='portada',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto portada (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='historicalinnovativeprojects',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=23, verbose_name='Título (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(280, 'La descripción debe tener al menos 280 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='portada',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects', verbose_name='Foto portada (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='title',
            field=models.CharField(blank=True, max_length=23, unique=True, verbose_name='Título (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='revisionsectiontwo',
            name='approved_gallery',
            field=models.BooleanField(default=True, verbose_name='Fotos de la galería con problemas'),
        ),
        migrations.AlterField(
            model_name='revisionsectiontwo',
            name='approved_portada',
            field=models.BooleanField(default=True, verbose_name='Foto de portada con problemas'),
        ),
        migrations.AlterField(
            model_name='revisionsectiontwo',
            name='approved_web_source',
            field=models.BooleanField(default=True, verbose_name='Error en la fuente o enlace'),
        ),
    ]
