# Generated by Django 4.2.2 on 2023-09-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_historicaltype_historicalproject_historicalprogram_and_more'),
        ('innovative_projects', '0008_alter_historicalinnovativeprojects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinnovativeprojects',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.program', verbose_name='Programa (obligatorio)'),
        ),
        migrations.RemoveField(
            model_name='innovativeprojects',
            name='program',
        ),
        migrations.AddField(
            model_name='innovativeprojects',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.program', verbose_name='Programa (obligatorio)'),
        ),
    ]
