# Generated by Django 4.2.2 on 2023-09-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovative_projects', '0009_historicalinnovativeprojects_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinnovativeprojects',
            name='state',
        ),
        migrations.RemoveField(
            model_name='innovativeprojects',
            name='state',
        ),
    ]
