# Generated by Django 4.2.2 on 2023-10-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovative_projects', '0010_remove_historicalinnovativeprojects_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInnovativeProjects',
        ),
    ]
