# Generated by Django 4.1.3 on 2023-05-21 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_region_checklistdocuments_and_more'),
        ('regioncomuna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_state', models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Ok'), ('2', 'No aplica')], max_length=1, verbose_name='Estado')),
                ('item_issuance_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('item_annotations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('item_link', models.URLField(blank=True, null=True, verbose_name='Link a archivo')),
                ('project_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.checklistdocuments', verbose_name='Ítem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('projectname', models.CharField(max_length=200, unique=True, verbose_name='Nombre (obligatorio)')),
                ('description', models.TextField(verbose_name='Descripción (obligatorio)')),
                ('portada', models.ImageField(null=True, upload_to='user_projects', verbose_name='Foto miniatura (obligatorio)')),
                ('check_list_project', models.ManyToManyField(to='user_projects.checklistprojects', verbose_name='Checklist de proyecto')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.comuna', verbose_name='Comuna')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.program', verbose_name='Programa (obligatorio)')),
                ('reference_projects', models.ManyToManyField(to='projects.project', verbose_name='Proyectos de referencia')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.type', verbose_name='Tipo de Proyecto (obligatorio)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
