# Generated by Django 4.1.3 on 2023-05-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistprojects',
            options={'verbose_name': 'Checklist de Proyecto', 'verbose_name_plural': 'Checklist de Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='userprojects',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
