# Generated by Django 4.1.3 on 2023-06-20 14:45

import applications.users.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupation', models.CharField(max_length=20, unique=True, verbose_name='Profesión')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=15, unique=True, validators=[applications.users.functions.validar_rut])),
                ('nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_usuario', models.CharField(choices=[('SUBDERE', 'SUBDERE'), ('BANCO', 'Banco de Proyectos')], default='Banco de Proyectos', max_length=20, verbose_name='SUBDERE o Banco de Proyectos')),
                ('password', models.CharField(blank=True, max_length=200)),
                ('email', models.TextField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuario administrador')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
