# Generated by Django 4.1.3 on 2023-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
