# Generated by Django 4.1.3 on 2023-07-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tipo_usuario'),
        ('users', '0002_user_institucion'),
    ]

    operations = [
    ]
