# Generated by Django 4.2.2 on 2023-08-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20230731_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name': 'Profesión', 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
