# Generated by Django 4.2.2 on 2023-09-27 20:07

from django.db import migrations

# Creación de grupos de administración
def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Editor General')
    Group.objects.get_or_create(name='Editor Programa')
    Group.objects.get_or_create(name='Profesional')
    Group.objects.get_or_create(name='Profesional Temporal')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profesion_options_alter_user_options'),
    ]

    operations = [
        migrations.RunPython(create_groups),
        migrations.RemoveField(
            model_name='user',
            name='tipo_usuario',
        ),
    ]
