# Generated by Django 4.1.3 on 2023-06-24 00:00

import applications.projects.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regioncomuna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Guías')),
                ('guide', models.FileField(blank=True, null=True, upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.projects.models.validate_file_size_five], verbose_name='Documento')),
            ],
        ),
        migrations.CreateModel(
            name='PrioritizedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritized_tag', models.CharField(max_length=20, unique=True, verbose_name='Tag para proyectos priorizados')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=200, unique=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre (obligatorio)')),
                ('id_subdere', models.CharField(max_length=200, unique=True, verbose_name='ID SUBDERE (obligatorio)')),
                ('description', models.TextField(verbose_name='Descripción (obligatorio)')),
                ('public', models.BooleanField(default=True)),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube')),
                ('portada', imagekit.models.fields.ProcessedImageField(null=True, upload_to='projects', verbose_name='Foto miniatura (obligatorio)')),
                ('beforeimage', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen Antes')),
                ('afterimage', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen Después')),
                ('eett', models.FileField(null=True, upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.projects.models.validate_file_size_five], verbose_name='EETT')),
                ('presupuesto', models.FileField(null=True, upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.projects.models.validate_file_size_five], verbose_name='Presupuesto')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.comuna', verbose_name='Comuna')),
                ('prioritized_tag', models.ManyToManyField(to='projects.prioritizedtag', verbose_name='Tag proyecto priorizado')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.program', verbose_name='Programa (obligatorio)')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tipo de Proyecto')),
                ('icon_type', models.CharField(default='other_admission', max_length=200, verbose_name='Icono ( Nombre icono)')),
                ('guides', models.ManyToManyField(related_name='guides', to='projects.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Projectimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_carousel', imagekit.models.fields.ProcessedImageField(upload_to='projects', verbose_name='Galeria de imagenes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Projectfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Nombre (obligatorio)')),
                ('file', models.FileField(upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.projects.models.validate_file_size_twenty])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.type', verbose_name='Tipo de Proyecto (obligatorio)'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.year', verbose_name='Año (obligatorio)'),
        ),
        migrations.CreateModel(
            name='ChecklistDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentname', models.CharField(max_length=50, unique=True, verbose_name='Nombre documento')),
                ('description', models.TextField(verbose_name='Descripción documento')),
                ('file', models.ManyToManyField(blank=True, to='projects.guide', verbose_name='Guías de referencia')),
            ],
        ),
    ]
