# Generated by Django 4.1.3 on 2023-05-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0001_initial'),
        ('projects', '0002_alter_project_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.region', verbose_name='Región'),
        ),
    ]
