# Generated by Django 4.2.2 on 2023-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='icon_program',
            field=models.FileField(blank=True, default=None, null=True, upload_to='icon-program/'),
        ),
    ]
