# Generated by Django 4.2.2 on 2023-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_prioritized_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prioritized_tag',
            field=models.ManyToManyField(blank=True, to='projects.prioritizedtag', verbose_name='Tag proyecto priorizado'),
        ),
    ]
