# Generated by Django 4.2.2 on 2023-08-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_program_icon_program'),
        ('projects', '0004_alter_project_prioritized_tag'),
    ]

    operations = [
    ]
