# Generated by Django 4.2.2 on 2023-08-30 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_checklistdocuments_options_alter_guide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='created_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Año de creación (obligatorio)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Año de creación (obligatorio)'),
            preserve_default=False,
        ),
    ]
