# Generated by Django 4.2.2 on 2023-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_innovativeprojects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinnovativeprojects',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='innovativeprojects',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
