# Generated by Django 4.2.2 on 2023-09-05 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_historicalinnovativeprojects_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinnovativeprojects',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(280, 'La descripción debe tener al menos 280 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='innovativeprojects',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(280, 'La descripción debe tener al menos 280 caracteres.')]),
        ),
    ]
