# Generated by Django 4.2.2 on 2023-09-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_historicalinnovativeprojects_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovativegaleryimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='innovativeprojects',
            name='program',
        ),
        migrations.RemoveField(
            model_name='innovativewebsource',
            name='project',
        ),
        migrations.DeleteModel(
            name='HistoricalInnovativeProjects',
        ),
        migrations.DeleteModel(
            name='InnovativeGaleryImage',
        ),
        migrations.DeleteModel(
            name='InnovativeProjects',
        ),
        migrations.DeleteModel(
            name='InnovativeWebSource',
        ),
    ]
