# Generated by Django 4.2.2 on 2023-09-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20230912_1222'),
        ('projects', '0013_rename_image_carousel_projectimage_image_and_more'),
    ]

    operations = [
    ]
