# Generated by Django 4.2.2 on 2023-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_merge_20230915_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalguide',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprioritizedtag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='year',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalChecklistDocuments',
        ),
        migrations.DeleteModel(
            name='HistoricalGuide',
        ),
        migrations.DeleteModel(
            name='HistoricalPrioritizedTag',
        ),
        migrations.DeleteModel(
            name='HistoricalProgram',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
        migrations.DeleteModel(
            name='HistoricalType',
        ),
    ]
