# Generated by Django 4.2.2 on 2023-09-29 15:18

import applications.projects.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_checklistdocuments_state_remove_guide_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa', to='projects.program', verbose_name='Programa (opcional)'),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.program', verbose_name='Programa (opcional)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='planimetria',
            field=models.TextField(max_length=100, null=True, validators=[applications.projects.functions.validate_file_size_twenty], verbose_name='Planimetría'),
        ),
        migrations.AddField(
            model_name='project',
            name='planimetria',
            field=models.FileField(null=True, upload_to='project_documents', validators=[applications.projects.functions.validate_file_size_twenty], verbose_name='Planimetría'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre (obligatorio)'),
        ),
    ]
