# Generated by Django 4.2.2 on 2023-09-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_guide_program_historicalguide_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalchecklistdocuments',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguide',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguide',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalprogram',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='program',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='type',
            name='guides',
        ),
        migrations.DeleteModel(
            name='ChecklistDocuments',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='HistoricalChecklistDocuments',
        ),
        migrations.DeleteModel(
            name='HistoricalGuide',
        ),
    ]
