# Generated by Django 4.2.2 on 2023-10-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_guide_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprogram',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='year',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='program',
        ),
        migrations.DeleteModel(
            name='HistoricalPrioritizedTag',
        ),
        migrations.DeleteModel(
            name='HistoricalProgram',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
        migrations.DeleteModel(
            name='HistoricalType',
        ),
    ]
